# Generated by Django 4.1.3 on 2023-03-31 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_post_content_mg_alter_post_mg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mg_state", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="mg",
        ),
        migrations.DeleteModel(
            name="MG",
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="network.post"
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user_mg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mg_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
