# Generated by Django 4.1.3 on 2023-04-03 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_like_remove_post_mg_delete_mg_like_post_like_user_mg"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="following_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
