# Generated by Django 4.1.3 on 2023-04-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_alter_user_followers_alter_user_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mg_state",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="like",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
