# Generated by Django 4.1.3 on 2023-04-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_post_mg_state_alter_like_id_alter_post_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="mg_state",
        ),
    ]
