# Generated by Django 4.1.3 on 2023-04-18 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_remove_post_mg_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user_poster",
        ),
        migrations.AddField(
            model_name="post",
            name="user_poster_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="poster_uploaded_id",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="user_poster_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="poster_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
