# Generated by Django 4.1.3 on 2023-04-19 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0011_alter_post_user_poster_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="user_poster_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user_poster_name",
        ),
        migrations.AddField(
            model_name="post",
            name="user_poster",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="poster_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
