# Generated by Django 4.1.3 on 2023-04-22 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0022_alter_followperfil_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followperfil",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="followers_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="followperfil",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="following_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
