# Generated by Django 4.1.3 on 2023-04-25 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0023_alter_followperfil_followers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="network.post",
            ),
        ),
    ]
