# Generated by Django 4.2.1 on 2023-09-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0029_remove_user_followers_remove_user_following_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Follow_profile",
            new_name="FollowProfile",
        ),
    ]
