# Generated by Django 4.2.1 on 2023-09-23 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0031_userfollowing_delete_followprofile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollowing",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userfollowing",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfollowing",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="userfollowing",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="userfollowing",
            name="following",
        ),
        migrations.AddField(
            model_name="userfollowing",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
